baseurl = "/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
paginate = "10"
theme = "mainroad"
title = "PEI Developers"
[[menu.main]]
name = "Meetup"
url = "https://www.meetup.com/pei-developers"
weight = 3
[[menu.main]]
name = "Twitter"
url = "https://www.twitter.com/peidevs"
weight = 4
[[menu.main]]
name = "Github"
url = "https://www.github.com/peidevs"
weight = 5
[[menu.main]]
name = "Code of Conduct"
url = "/code/"
weight = 2
[[menu.main]]
name = "About"
url = "/about/"
weight = 1
[[menu.side]]
name = "Scooter"
url = "https://peidevs.github.io/Event_Resources/"
[[menu.side]]
name = "People's Scooter"
url = "http://peidevs.github.io/Scooter"
[[menu.side]]
name = "Request Slack Invite"
url = "https://docs.google.com/forms/d/1hNruzn7fb8Wu7BbuGVvgbeO0-HTNnDrcCJAQ24wZTBs/viewform"
[[menu.side]]
name = "Flickr"
url = "http://www.flickr.com/photos/100794919@N05/"
[params]
authorbox = false
description = "Home of the PEI Developers Group."
leftsidebar = false
opengraph = false
post_navigation = true
subtitle = "est. 2012"
[params.widgets]
categories = true
important = true
recent_articles = true
recent_articles_num = 10
search = false
tags = false
tags_counter = false
